### ISSUE TITLE
How to specify paths?

### ISSUE THREAD

**Issue by Romkond** [dominikwilkowski/grunt-css-purge#3]
Hi there, thank you for the plugin. I've got a question: how to specify paths in plugin's settings?
I tried this:
```
	css_purge: {
	options: {
		"verbose": false,
		"no_duplicate_property": true,
	},
	files: {
			'public_html/test/www-critical/purge.css': 'public_html/test/www-critical/critical.min.css',
		},
},
```
or this:
```
	css_purge: {
	options: {
		"verbose": false,
		"no_duplicate_property": true,
	},
	files: [{
		cwd: 'public_html/test/www-critical/',
		src: ['critical.min.css'],
		dest: 'public_html/test/www-critical/purge.css'
	}],
},
```
The 1st version produces nothing: "Done withour errors", but there's no the purge.css in that directory. The 2nd way is

> "Warning: pattern.indexOf is not a function Use --force to continue.
> Aborted due to warnings."

**Comment by dominikwilkowski** [comment]
Hi @Romkond 

Sorry for the late reply. I just published version 1.0.0. This should fix your files issues. I don't think the plugin was ever really working before :)

For your convenience I included some examples in the Readme file on how to use the task. I'll past them here as well for you.

A single file:

```js
default_options: {
	options: {},
	src: 'site.css',
	dest: 'site.min.css',
},
```

Multiple files:

```js
multiple_files: {
	options: {},
	src: [
		'site1.css',
		'site2.css',
	],
	dest: 'site.min.css',
},
```

Multiple files:

```js
multiple_files2: {
	options: {},
	files: {
		'site.min.css': ['site1.css', 'site2.css'],
	},
},
```

Multiple files with a wildcard:

```js
multiple_files3: {
	options: {},
	files: [{
		src: ['css/**/*.css'],
		dest: 'site.min.css',
	}],
},
```

Custom options:

```js
custom_options: {
	options: {
		trim_comments: false,
		generate_report: true,
	},
	src: 'site.css',
	dest: 'site.min.css',
},
```

I'll close this issue for now. Feel free to open again if you have issues.

**Comment by dcress** [comment]
@dominikwilkowski First off, thanks for this plugin. It's awesome. Really great work here. 

Second, not sure if i'm missing something, but is there a way to run CSS Purge on an entire dir and have it output multiple files with the same name as the src file? As in: 

```
files: [{
	expand: true,
	cwd: "css/pages",
	src: "*.css",
	dest: "css/min", 
	ext: ".min.css"
}]
```

so if this was my `css/pages` dir: 
- css
    - pages
        - page-1.css
        - page-2.css
        - page-3.css


It would output: 
- css
    - min
        - page-1.min.css
        - page-2.min.css
        - page-3.min.css


Let me know if i need to reword/clarify that. Essentially, i'm trying to avoid creating a specific call to every file in a dir, when I want to run the task on every file in that dir.

**Comment by dominikwilkowski** [comment]
Hey there. Sorry I’m on vacation right now and will be back next week but have a look at the grunt docs. This plugin should use the very same way grunt is being used. If not I’ll fix it :)


--

Dominik Wilkowski

M\\  +61 432 717 489
W\\  DOMINIK-WILKOWSKI.COM
E\\   HI@DOMINIK-WILKOWSKI.COM

**Comment by dcress** [comment]
@dominikwilkowski Thanks for your response. It's currently giving me the error: 

`Warning: pattern.indexOf is not a function Use --force to continue.
Aborted due to warnings.` (same error as is related to this issue), so it seems like it isn't quite working. 

Enjoy your vacation!

**Comment by dominikwilkowski** [comment]
Hey @dcress 

sorry for the late reply. It's been busy.
I can't see any other grunt plugins do this and I think you would have to build this functionality in as it doesn't seem to exist with grunts API. I could be wrong.

**Comment by dominikwilkowski** [comment]
Actually I take that back. I just tried it and it all works just as you describe it :)
so if I have a folder, say `css/` and a bunch of files in there, say `test1.css` and `test2.css` then we run this in grunt:

```js
multiple_files4: {
	options: {},
	files: [{
		expand: true,
		cwd: "css/", // all *.css files inside the css/ folder will be purged
		src: "*.css",
		dest: "output/", //and placed into the output folder
		ext: ".min.css",
	}],
},
```

Then we get this output:

```shell
Running "css_purge:multiple_files4" (css_purge) task
>> File successfully purged to "output/test.min.css"
>> File successfully purged to "output/test2.min.css"
```

and the two files are written in the `output/` folder.

I have added this example to the readme as well
