### ISSUE TITLE
Launched new CSS-PURGE version

### ISSUE THREAD

**Issue by AndrewEQ** [dominikwilkowski/grunt-css-purge#4]
Hey Dom,

Just launched the new version!

https://github.com/rbtech/css-purge

**Comment by AndrewEQ** [comment]
Just updated to v3!

Here's the link to the image you can use for when you update like: https://github.com/rbtech/gulp-css-purge

https://github.com/rbtech/css-purge/blob/master/assets/images/grunt-css-purge.png

**Comment by dominikwilkowski** [comment]
Working on it today

**Comment by dominikwilkowski** [comment]
fixed via 6b60ea4e36a30568a7c58b93c765c76b80fc75bb

**Comment by AndrewEQ** [comment]
Cool man and a Happy New Year to you! All the best!
