### ISSUE TITLE
Patch - 3.0.4

### ISSUE THREAD

**Issue by AndrewEQ** [dominikwilkowski/grunt-css-purge#5]
Hey Dom, 

Just patched the following issue: https://github.com/rbtech/css-purge/issues/16

So ya just need to update your dependency version to 3.0.4

**Comment by dominikwilkowski** [comment]
Hey

Is it save to pin the dependency on the major version? Will you use semver for your versions @AndrewEQ ?

**Comment by AndrewEQ** [comment]
I'm using semver, I like NPMs little table with examples: https://docs.npmjs.com/getting-started/semantic-versioning

Is it safe in terms of the public/major functions being "set in stone" now?

Hmm, I think I'd still like the option to be able to "break things" with a major version if its going to benefit us in terms of developer-friendly-ness or in terms of performance gains, so I think its always safer to pin it to a minor version.

Or how about this: you can pin it to the major version, and if I make any breaking changes between major versions, I will let you know of them? Less of me notifying and less of you changing, so we'll work as if the "glass is half full" :D

**Comment by dominikwilkowski** [comment]
Haha I think you misunderstood :)

> Is it save to pin the dependency on the major version? Will you use semver for your versions @AndrewEQ ?

I suggested to pin `css-purge` it it's major version inside `grunt-css-purge`.
That would mean:
```
"dependencies": {
	"css-purge": "~3"
},
```

I then asked if that was safe from your perspective as this means you will have to adhere to semver. (Mayor = breaking changes, Minor = additional feature but backwards compatible, Patch = fix and backwards compatible).
If so then when ever you want to break the API you will have to bump major and I would have to actually go into the plugin code and check that everything works an then also bump the major version.

All other changes like bug fixes or added features wont cause me to change anything and your plugin land will be automatically up to date asap.

I think in your last paragraph you sorta allude to the same idea :)

**Comment by AndrewEQ** [comment]
Oh, haha, yeah on the dependencies, I thought you wanted to make it: "css-purge": "*", which isn't safe but if I don't make any breaking changes between major versions, then it would "technically" be safe.

I think we're on the same page though, so carry on then :D

![Carry on then](https://dgeiu3fz282x5.cloudfront.net/g/l/lgN170.jpg)
